### ISSUE TITLE
Support Bitcoin Core v28.0

### ISSUE THREAD

**Issue by thobson88** [alan-turing-institute/trustchain#216]
Our ION installation docs recommend Bitcoin Core v24.0.1 because Sidetree requires a legacy wallet type which is deprecated in more recent versions.

Already in v24.0.1 we have to pass the `descriptors=false` parameter to the CLI when creating the wallet:
```
bitcoin-cli -named createwallet wallet_name="sidetreeDefaultWallet" descriptors=false
```

In the latest version v28.0 (as of Nov 2024), the above command fails unless `bitcoind` is started with the `deprecatedrpc=create_bdb` flag, so the docs will need to be updated [here](https://alan-turing-institute.github.io/trustchain/ion/#start-bitcoin-core) so the command to create the alias for `bitcoind` becomes:
```
echo 'alias bitcoind="/usr/local/bin/bitcoind -conf=$BITCOIN_DATA/bitcoin.conf -deprecatedrpc=create_bdb"' >> $SHELL_CONFIG; source $SHELL_CONFIG
```

**UPDATE:** a better solution is to put this in `bitcoin.conf`:
```
deprecatedrpc=create_bdb
```

With this change, the above `createwallet` CLI command succeeds (albeit with the warning about legacy wallet type being deprecated, which is already mentioned in our docs).

However, there is this new `invalid_magic_bytes` error when starting the ION bitcoin microservice:
```
Parsing file: blk00890.dat
Sidetree-Bitcoin node initialization failed with error: {"stack":"Error: 3f6421a4 at cursor position 0 is not valid bitcoin mainnet, testnet or regtest magic bytes\n    at BitcoinRawDataParser.parseRawDataFile (/home/tim/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinRawDataParser.js:33:23)\n    at BitcoinBlockDataIterator.previous (/home/tim/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinBlockDataIterator.js:30:59)\n    at BitcoinProcessor.<anonymous> (/home/tim/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:153:57)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/tim/ion/node_modules/@decentralized-identity/sidetree/dist/lib/bitcoin/BitcoinProcessor.js:5:58)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)","message":"3f6421a4 at cursor position 0 is not valid bitcoin mainnet, testnet or regtest magic bytes","code":"bitcoin_raw_data_parser_invalid_magic_bytes"}
```

<img width="845" alt="Screenshot 2024-11-22 at 15 41 13" src="https://github.com/user-attachments/assets/e6581632-aa5c-4b1a-bf5c-0b87a4dde483">

**Comment by thobson88** [comment]
The `invalid_magic_bytes` error (above) is due to new block storage rules in Bitcoin Core v28.0. See the [release notes](https://bitcoincore.org/en/releases/28.0/) under section "Blockstorage", and the relevant [PR #28052](https://github.com/bitcoin/bitcoin/pull/28052).

Basically, block files are now XOR'd by default, using a randomly-generated pattern, making them unreadable by ION.

The solution appears to be to add this line in `bitcoin.conf`:
```
blocksxor=0
```
This sets the XOR pattern to zero, so essentially turns this feature off.

If a v28 node is already synched, without this config parameter, you need to resync it from scratch. To do this, delete the blocks `.dat` files in `$BITCOIN_DATA/blocks` and then start the daemon with -reindex flag:
```
bitcoind -reindex
```

**Comment by thobson88** [comment]
An additional config setting is needed else DID verification via the trustchain CLI fails with:
```
Error: LedgerClientError("getnetworkinfo")
```
The fix is to add this line in `bitcoin.conf`:
```
deprecatedrpc=warnings
```
See the [release notes](https://bitcoincore.org/en/releases/28.0/) for details.
